version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.5
      - image: crate:latest
        command: docker run -p=4200:4200 -d=true crate

    working_directory: /go/src/github.com/chughpiyush/go-crate

    steps:
      - run:
         environment:
           CRATE_URL: "http://localhost:4200/"

      - checkout
      - run:
            command: dockerize -wait tcp://localhost:4200 -timeout 1m
      - run: go get -v -t -d ./...
      - run: go test -v ./...