version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.5

    working_directory: /go/src/github.com/chughpiyush/go-crate

    steps:
      - setup_remote_docker:
      - run:
         environment:
           CRATE_URL: "http://localhost:4200/"
         command: |
           docker pull crate
           docker run -p=4200:4200 -d=true crate

      - checkout
      - run:
            command: dockerize -wait tcp://localhost:4200 -timeout 1m
      - run: go get -v -t -d ./...
      - run: go test -v ./...